# Generated by Django 3.0.4 on 2020-03-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_institutionemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='identifier',
            field=models.CharField(default='slu', max_length=30),
            preserve_default=False,
        ),
    ]
