# Generated by Django 3.0.4 on 2020-03-19 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_form', models.FileField(upload_to='forms/')),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=256)),
                ('patient_dob', models.DateField()),
                ('today_date', models.DateField()),
                ('consent_status', models.IntegerField(choices=[(1, 'Consent not yet given'), (2, 'Consent given by patient'), (3, 'Consent refused'), (4, 'Consent given by guardian/relative (see relationship)'), (5, 'Inability to give consent (see reason)')])),
                ('consent_video', models.FileField(upload_to='videos/')),
                ('password', models.CharField(max_length=32)),
                ('relationship_to_patient', models.CharField(max_length=32)),
                ('inability', models.CharField(max_length=256)),
                ('proceedure_name', models.CharField(max_length=256)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nurse', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consent.Operation')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='physician', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
