# Generated by Django 3.0.4 on 2020-03-19 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consent', '0002_operation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsent',
            name='proceedure_name',
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='consent_status',
            field=models.IntegerField(choices=[(1, 'Consent not yet given'), (2, 'Consent given by patient'), (3, 'Consent refused'), (4, 'Consent given by guardian/relative (see relationship)'), (5, 'Inability to give consent (see reason)')], default=1),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='consent_video',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='inability',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='relationship_to_patient',
            field=models.CharField(default='self', max_length=32),
        ),
    ]
