# Generated by Django 3.0.4 on 2020-03-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0004_auto_20200319_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsent',
            name='relative_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
