# Generated by Django 3.0.4 on 2020-03-19 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consent', '0006_auto_20200319_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='nurse', to=settings.AUTH_USER_MODEL),
        ),
    ]
