# Generated by Django 3.0.4 on 2020-03-19 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_form', models.FileField(upload_to='forms/')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=256)),
                ('patient_dob', models.DateField()),
                ('patient_mrn', models.CharField(max_length=64)),
                ('physician_signature', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('procedure', models.CharField(max_length=512)),
                ('diagnosis', models.CharField(max_length=256)),
                ('risk_ben_alt', models.CharField(max_length=4096)),
                ('anesthsia_type', models.IntegerField(choices=[(1, 'General Anesthesia'), (2, 'Local Anesthesia'), (3, 'Sedation'), (4, 'No Anethesia')], default=4)),
                ('patient_signature', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('inability_reason', models.CharField(blank=True, max_length=256, null=True)),
                ('representative_name', models.CharField(blank=True, max_length=256, null=True)),
                ('relationship_to_patient', models.CharField(blank=True, max_length=32, null=True)),
                ('witness_signature', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('today_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('password', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('attending_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attending_physician', to=settings.AUTH_USER_MODEL)),
                ('consent_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='consent.Operation')),
                ('consenting_physician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='consenting_physician', to=settings.AUTH_USER_MODEL)),
                ('witness_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='witness', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
