# Generated by Django 3.0.4 on 2020-03-20 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0010_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsent',
            name='anesthsia_type',
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='ability_to_consent',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='anesthesia_type',
            field=models.IntegerField(choices=[(1, 'General Anesthesia'), (2, 'Local Anesthesia'), (3, 'Sedation'), (4, 'No Anesthesia')], default=4),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='relationship_to_patient',
            field=models.CharField(default='self', max_length=256),
        ),
    ]
