# Generated by Django 3.0.4 on 2020-03-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0011_auto_20200320_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='ability_to_consent',
            field=models.IntegerField(choices=[(2, 'No'), (1, 'Yes')], default=1),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='relationship_to_patient',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
