# Generated by Django 3.0.4 on 2020-03-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0012_auto_20200320_0459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsent',
            name='password',
        ),
        migrations.AddField(
            model_name='patientconsent',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
