# Generated by Django 3.0.4 on 2020-03-25 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_institutionemail'),
        ('consent', '0015_patientconsent_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsent',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Institution'),
        ),
    ]
