# Generated by Django 3.0.4 on 2020-03-26 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0017_auto_20200325_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsent',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='patientconsent',
            name='ability_to_consent',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
    ]
