# Generated by Django 3.0.4 on 2020-04-03 22:55

import consent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0019_auto_20200326_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='identifier',
            field=models.CharField(default=consent.models.generate_form_id, max_length=10, unique=True),
        ),
    ]
