# Generated by Django 3.0.4 on 2020-04-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0020_auto_20200403_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='ability_to_consent',
            field=models.IntegerField(choices=[(1, 'Yes'), (2, 'No')], default=1),
        ),
    ]
