# Generated by Django 3.0.4 on 2020-04-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consent', '0021_auto_20200403_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsent',
            name='ability_to_consent',
            field=models.IntegerField(choices=[(2, 'No'), (1, 'Yes')], default=1),
        ),
    ]
